
@api = fresqueduclimat.org/wiki/en/api.php
@pageTitle = En-en_adult_card_1_human_activities
@pageTitle2 = En-en_adult_card_14_energy_budget

@pageTitle_CardsList = Adult_game

@query = {{api}}?action=query&format=json&titles={{pageTitle}}

### get info CardsList Page
https://{{api}}?action=query&format=json&titles={{pageTitle_CardsList}}&prop=info
# Get the pageid to put it in config cardsListPageId=2

### get info
https://{{api}}?action=query&format=json&titles={{pageTitle2}}&prop=info

### Query help
https://www.mediawiki.org/w/api.php?action=help&modules=query

### Links - 9 items
https://{{query}}&prop=links

### categories - Nothing
https://{{query}}&prop=categories


### extlinks - OK
https://{{query}}&prop=extlinks

### extlinks - bof
https://{{query}}&prop=info

### iwlinks -nothing
https://{{query}}&prop=iwlinks

### pageprops - get page id from the title
https://{{api}}?action=query&format=json&titles={{pageTitle}}&prop=pageprops

### allimages - all in namespace
https://{{query}}&list=allimages

### change tags -
https://{{api}}?action=query&list=tags&tgprop=displayname|description|hitcount|defined

### languageinfo- list all lang
https://{{query}}&meta=languageinfo

###

http://{{query}}&prop=revisions&rvprop=content&rvsection=0

###
https://en.wikipedia.org/w/api.php?action=parse&page=Template:Infobox%20hydrogen&format=json

### parse page (by id)
@wikiId = 21
https://{{api}}?action=parse&format=json&pageid={{wikiId}}

### parse section meta
https://{{api}}?action=parse&format=json&pageid={{wikiId}}&prop=sections

### parse section 0 - Entete
https://{{api}}?action=parse&format=json&pageid={{wikiId}}&section=0&prop=text

### parse section 1 - Explications
https://{{api}}?action=parse&format=json&pageid={{wikiId}}&section=1&prop=text

### parse section 2 - Autres_liens_possibles
https://{{api}}?action=parse&format=json&pageid={{wikiId}}&section=2&prop=text

### parse section 3 -
https://{{api}}?action=parse&format=json&pageid={{wikiId}}&section=3&prop=text

### parse section 4 -
https://{{api}}?action=parse&format=json&pageid={{wikiId}}&section=3&prop=text

# Entete
# Definition
# Explications
# Conseils pour l'animation
# Autres_liens_possibles

### sections page 1
https://{{api}}?action=parse&format=json&pageid=4&prop=sections

### sections page 5
https://{{api}}?action=parse&format=json&pageid=18&prop=sections

### sections page 6
https://{{api}}?action=parse&format=json&pageid=21&prop=sections

### sections page 7
https://{{api}}?action=parse&format=json&pageid=23&prop=sections

### parse  page 7 - section index 1
https://{{api}}?action=parse&format=json&pageid=23&section=1&prop=text

### parse  page 7 - section index 2
https://{{api}}?action=parse&format=json&pageid=23&section=2&prop=text

### sections page 20
https://{{api}}?action=parse&format=json&pageid=48&prop=sections

### parse page 20 - section index 5
https://{{api}}?action=parse&format=json&pageid=48&section=5&prop=text
