
@api = fresqueduclimat.org/wiki/api.php

### 1. Set the title

@pageTitle = Fr-fr_adulte_carte_5_énergies_fossiles

### 2. call this
https://{{api}}?action=query&format=json&titles={{pageTitle}}&prop=info

### 3. fill th page Id with the response
@pageid = 18

### 4. Call get sections

https://{{api}}?action=parse&format=json&prop=sections&pageid={{pageid}}

### 5. update the test file...
