
@apiFr = fresqueduclimat.org/wiki/api.php
@apiEn = fresqueduclimat.org/wiki/en/api.php

### 1. Set the title

@pageTitle = Fr-fr_adulte_carte_6_d%C3%A9forestation

### 2. call this
https://{{api}}?action=query&format=json&titles={{pageTitle}}&prop=info

### 3. fill th page Id with the response
@pageId = 21

### 4. Call get sections

https://{{apiFr}}?action=parse&format=json&prop=sections&pageid={{pageId}}

### 5. Fill the sections[].index where the line & anchor is ad hoc

@sectionIndex = 3

### 6. Call the parse endpoint with pageid and section index

https://{{apiFr}}?action=parse&format=json&prop=text&pageid={{pageId}}&section={{sectionIndex}}

### 7. update the test file if necessary
