
@api = fresqueduclimat.org/wiki/en/api.php

### 1. Set the title

@pageTitle = En-en_adult_card_5_fossil_fuels

### 2. call this
https://{{api}}?action=query&format=json&titles={{pageTitle}}&prop=info

### 3. fill th page Id with the response
@pageid = 16

### 4. Call get sections

https://{{api}}?action=parse&format=json&prop=sections&pageid={{pageid}}

### 5. update the test file...
