name: Tests

# Controls when the action will run.
on:
  schedule:
    # Runs every day at 1pm
    - cron: "0 13 * * *"

  # to run the workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: import EN
        run: yarn import-en
        env:
          CI: true

      - name: check import EN
        run: yarn test-res-en
        env:
          CI: true
